// Package database owns the Postgres connection, entity base type, and
// driver-error translation helpers.
package database

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

// BaseEntity is the header every persistent entity embeds. Provides a UUIDv7 PK
// (generated by the hook) and timestamps (created_at by DB default,
// updated_at bumped by the hook on UPDATE).
type BaseEntity struct {
	ID        uuid.UUID `bun:"id,pk,type:uuid,nullzero"`
	CreatedAt time.Time `bun:"created_at,nullzero,notnull,default:current_timestamp"`
	UpdatedAt time.Time `bun:"updated_at,nullzero,notnull,default:current_timestamp"`
}

// BeforeAppendModel assigns a UUIDv7 on insert and bumps updated_at on
// update. CreatedAt is intentionally left to the DB default on insert so
// bun's auto-RETURNING hydrates it from the DB clock — the single source of
// truth for creation time.
func (b *BaseEntity) BeforeAppendModel(_ context.Context, query bun.Query) error {
	switch query.(type) {
	case *bun.InsertQuery:
		if b.ID == uuid.Nil {
			id, err := uuid.NewV7()
			if err != nil {
				return fmt.Errorf("uuid v7: %w", err)
			}
			b.ID = id
		}
	case *bun.UpdateQuery:
		b.UpdatedAt = time.Now().UTC()
	}
	return nil
}
